In [3]:
import numpy as np

In [4]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [5]:
m = np.array([[7,8,9],[10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [6]:
m.shape

(2, 3)

In [7]:
n = np.arange(30,0,-2)
n

array([30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [9]:
n = n.reshape(3,5)
n

array([[30, 28, 26, 24, 22],
       [20, 18, 16, 14, 12],
       [10,  8,  6,  4,  2]])

In [27]:
lspace = np.linspace(0,10,9)
lspace

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [29]:
lspace = np.resize(lspace,(3,4))
lspace

array([[ 0.  ,  1.25,  2.5 ,  3.75],
       [ 5.  ,  6.25,  7.5 ,  8.75],
       [10.  ,  0.  ,  1.25,  2.5 ]])

In [35]:
num = np.matrix([[11,121,134,123],[1,2,3,145],[1,3,4,5326],[26,52,7264,27]])
num

matrix([[  11,  121,  134,  123],
        [   1,    2,    3,  145],
        [   1,    3,    4, 5326],
        [  26,   52, 7264,   27]])

In [36]:
type(num)

numpy.matrix

In [40]:
print("Main Diagonal elements : \n", np.diag(num))
print("Main Diagonal elements above the diagonal: \n", np.diag(num,1))
print("Main Diagonal elements below the diagonal: \n", np.diag(num,-1))
print("Main Diagonal elements below the diagonal: \n", np.diag(num,-3))

Main Diagonal elements : 
 [11  2  4 27]
Main Diagonal elements above the diagonal: 
 [ 121    3 5326]
Main Diagonal elements below the diagonal: 
 [   1    3 7264]
Main Diagonal elements below the diagonal: 
 [26]


In [89]:
np.array([4,5,6] * 4)

array([4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6])

In [90]:
np.repeat([1,2,3], 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [45]:
p = np.ones([3,3], int)
p

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [46]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [48]:
np.vstack([p, 2*p, 3*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [58]:
x = np.array([1,2,3])
y = np.array([4,5,7])

In [62]:
print(x + y)
print(x - y)
print(x * y)        #Multiply corresponding elements of the matrix
print(x @ y)        #Sum of all elements of x * y (Dot product)

[ 5  7 10]
[-3 -3 -4]
[ 4 10 21]
35


In [63]:
print(x / y)
print(x**3)

[0.25       0.4        0.42857143]
[ 1  8 27]


In [ ]:
x.dot(y) # dot product

np.int64(35)

In [66]:
z = np.array([y, y**2])
z

array([[ 4,  5,  7],
       [16, 25, 49]])

In [67]:
print(len(z))

2


In [68]:
z.shape

(2, 3)

In [71]:
z.T # .T to get Transpose

array([[ 4, 16],
       [ 5, 25],
       [ 7, 49]])

In [72]:
z.T.shape #shape of Transpose

(3, 2)

In [74]:
z.T.dtype

dtype('int64')

In [78]:
z.astype('f').dtype

dtype('float32')

In [80]:
a = np.array([-4, -2, 1, 3, 5, 9])
a.sum()

np.int64(12)

In [83]:
int(a.max())

9

In [84]:
int(a.min())

-4

In [85]:
int(a.mean())

2

In [87]:
a.std()

np.float64(4.320493798938574)

In [108]:
import math
math.sqrt((sum((a - np.array([a.mean()] * len(a))) **2))/(len(a)-1))
# std deviation formula = sqrt of [(sum of squares of difference between elements of array and mean)/ (size of array - 1)]

4.732863826479693

In [109]:
s = np.arange(100)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [114]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [115]:
s[0], s[4], s[-1]

(np.int64(0), np.int64(16), np.int64(144))

In [116]:
s[1:5]

array([ 1,  4,  9, 16])

In [117]:
s[-4:]

array([ 81, 100, 121, 144])

In [118]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [121]:
s[-5::2]

array([ 64, 100, 144])

In [123]:
s[-5:-2]

array([ 64,  81, 100])

In [157]:
r = np.arange(100).reshape(10,10)
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [158]:
r[9, 4:-1]

array([94, 95, 96, 97, 98])

In [159]:
r[-1,::2]

array([90, 92, 94, 96, 98])

In [160]:
r[r>=30].reshape(10,7)

array([[30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [161]:
r[r>30] = 30
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [163]:
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [165]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [166]:
r

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [174]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [196]:
test = np.random.randint(0,100,(4,3))
test

array([[61, 97, 68],
       [ 4, 36, 35],
       [48, 46, 16],
       [23, 43,  6]])

In [199]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [61 97 68]
row 1 is [ 4 36 35]
row 2 is [48 46 16]
row 3 is [23 43  6]


In [200]:
test2 = test**2

In [201]:
for i,j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[61 97 68] + [3721 9409 4624] = [3782 9506 4692]
[ 4 36 35] + [  16 1296 1225] = [  20 1332 1260]
[48 46 16] + [2304 2116  256] = [2352 2162  272]
[23 43  6] + [ 529 1849   36] = [ 552 1892   42]


In [214]:
marks = np.array([[12,23,41],[46,24,73],[75,37,74],[23,44,44]])
marks

array([[12, 23, 41],
       [46, 24, 73],
       [75, 37, 74],
       [23, 44, 44]])

In [215]:
student_total = np.sum(marks, axis=1)
print("Total of each student:", student_total)

Total of each student: [ 76 143 186 111]


In [220]:
meanstud = np.mean(marks)
print("Mean of each student:", meanstud)

Mean of each student: 43.0


In [219]:
argmaxstud = np.argmax(student_total)
print("Max of each student:", argmaxstud)

Max of each student: 2
