<H3><b> Important points</H3>

<i> &emsp; 1. Minimum number of variables are used for quick understanding while revising<br>

In [ ]:
import numpy as np

In [19]:
# 1. Create a constant array
#  prints "[[7. 7.]]
#           [7. 7]]"
np.ones([2,2], float) *7

array([[7., 7.],
       [7., 7.]])

In [ ]:
# 2. Create an array filled with random values
# Might print "[[0.91949167 0.08143941]
#               [0.68744134 0.87236687]]"

#method 1
print(np.random.randint(0,10**8,(2,2))/(10**8))

#Method 2
print(np.random.default_rng().random([2,2]))

[[0.58810132 0.38859355]
 [0.45059192 0.51159467]]
[[0.51327123 0.82678705]
 [0.71202944 0.52318814]]


In [ ]:
# 3.Create a NumPy array containing the numbers from 10 to 50. Display:
# a. The array
# b. Number of elements
# c. Shape
# d. Dimension
# e. Data type

# a. The array
l = np.arange(10,50).reshape([4,10])
print("Array:",l)

# b. Number of elements
print("Number of elements in the array:", l.size)

# c. Shape
print("Shape of array:", l.shape)

# d. Dimension
print("Dimension of array:", l.ndim)

# e. Data type
print("Datatype of array:", l.dtype)


Array: [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Number of elements in the array: 40
Shape of array: (4, 10)
Dimension of array: 2
Datatype of array: int32


In [ ]:
# 4. Using NumPy, create: 
# a. 1D array containing 10 zeroes
# b. 3 x 3 array contain ones
# c. 4 x 4 identity matrix
# d. An array containing numbers from 5 to 50 with a step size of 5.

# a. 1D array containing 10 zeroes
print("1D array containing 10 zeroes:",np.repeat([0],10))

# b. 3 x 3 array contain ones
print("3 x 3 array contain ones:\n", np.ones([3,3], int))

# c. 4 x 4 identity matrix
print("4 x 4 identity matrix:\n", np.ones([4,4], int))

# d. An array containing numbers from 5 to 50 with a step size of 5.
print("An array contiaining numbers from 5 to 50 with a step size of 5:", np.arange(5,55,5))

1D array containing 10 zeroes: [0 0 0 0 0 0 0 0 0 0]
3 x 3 array contain ones:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
4 x 4 identity matrix:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
An array contiaining numbers from 5 to 50 with a step size of 5: [ 5 10 15 20 25 30 35 40 45 50]


In [ ]:
# 5. Create an array containing numbers from 1 tp 24. Reshape it into:
# a. 4 x 6
# b. 6 x 4
# c. 2 x 3 x 4

# a. 4 x 6
xyz = np.arange(1,25).reshape([4,6])
print("Shape:",xyz.shape,"Dim:",xyz.ndim,"\n", xyz)
print("\n")

# b. 6 x 4
xyzT = xyz.T
print("Shape:",xyzT.shape,"Dim:",xyzT.ndim,"\n", xyz.T)
print("\n")

# c. 2 x 3 x 4
xyz234=xyz.reshape([2,3,4])
print("Shape:",xyz234.shape,"Dim:",xyz234.ndim,"\n", xyz234)

Shape: (4, 6) Dim: 2 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


Shape: (6, 4) Dim: 2 
 [[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]


Shape: (2, 3, 4) Dim: 3 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
# 6. Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
# Write NumPy statements to display:
# a. First element
# b. Last element
# c. Third element
# d. First four elements
# e. Last three elements

marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
# a. First element
print("First element:", marks[0])

# b. Last element
print("Last element:", marks[-1])

# c. Third element
print("First element:", marks[2])

# d. First four elements
print("First four element:", marks[:4])

# e. Last three elements
print("Last three element:", marks[-3:])

First element: 78
Last element: 81
First element: 92
First four element: [78 85 92 67]
Last three element: [73 95 81]


In [ ]:
# 7. Create:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

# Calculate
# a + B
print("a + b:",a + b)

# a - b
print("a - b:",a - b)

# a * b
print("a * b:",a * b)

# a / b
print("a / b:",a / b)

a + b: [15 30 45 60 75]
a - b: [ 5 10 15 20 25]
a * b: [  50  200  450  800 1250]
a / b: [2. 2. 2. 2. 2.]


In [ ]:
# 8. Given:
salary = np.array([25000, 32000, 28000, 45000, 50000, 38000, 42000, 30000])

# Find:
# Total Salary
print("Total Salary:", salary.sum())

# Average Salary
print("Average Salary:", salary.mean())

# Highest Salary
print("Highest Salary:", salary.max())

# Lowest Salary
print("Lowest Salary:", salary.min())

# Median Salary
print("Median Salary:", np.median(salary))

# Standard Deviation
print("Standard Deviation:", salary.std())

Total Salary: 290000
Average Salary: 36250.0
Highest Salary: 50000
Lowest Salary: 25000
Median Salary: 35000.0
Standard Deviation: 8317.902379807063


In [ ]:
# 9. Given:
marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])
#Using NumPy boolean indexing, find:

# a. Marks greater than 75
print("Marks greater than 75:",marks[marks>75])

# b. Marks between 50 and 80
print("Marks between 50 and 80:",marks[(marks>50) & (marks<80)])

# c. Number of students who scored below 50
print("Number of students who scored below 50:", marks[marks<50].size)

# d. Percentage of students who scored 60 or above
print("Percentage of students who scored 60 or above:", (marks[marks>=60].size/marks.size)*100, "%")

Marks greater than 75: [78 89 90 76 84]
Marks between 50 and 80: [78 67 55 76]
Number of students who scored below 50: 3
Percentage of students who scored 60 or above: 60.0 %


In [ ]:
#10. The following array contains marks of four students in three subjects:

marks = np.array([
    [80, 95, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])

#Calculate:

#Total marks of each student
#Average marks of each student
#Average marks in each subject
#Student with the highest total
#Highest mark in each subject.

#Total marks of each student
student_total = np.sum(marks, axis=1)
print("Total of each student:", student_total)



#Average marks of each student
meanstud = np.mean(marks, axis=1)
print("Mean of each student:", meanstud)

#Average marks in each subject
meansub = np.mean(marks, axis=0)
print("Mean of each student:", meansub)

#Student with the highest total
argmaxstud = np.argmax(student_total)
print("Max student:", argmaxstud)

#Highest mark in each subject.
argmaxstud = np.argmax(marks, axis=0)
print("Max subject:", argmaxstud)

Total of each student: [265 207 265 173]
Mean of each student: [88.33333333 69.         88.33333333 57.66666667]
Mean of each student: [72.   79.25 76.25]
Max student: 0
Max subject: [2 0 0]


In [ ]:
#11. Create:

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

#Perform:

#Matrix addition
print("Addition:\n",A+B)

#Element-wise multiplication
print("Element wise multiplication:\n", A * B)

#Matrix multiplication
print("Matrix multiplication:\n", A @ B)

#Transpose of A.
print("Transpose of A:\n", A.T)

#explain the difference between: A * B and A @ B

# Answer: A * B multiplies the corresponding elements of the matrixes while A @ B carries out matrix multiplication.

Addition:
 [[ 6  8]
 [10 12]]
Element wise multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]


In [ ]:
#12. Daily temperatures for two weeks are:

temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])

#Find:
#Mean temperature
print("Mean temperature:", temperature.mean())

#Maximum and minimum temperatures
print("Maximum temperatures:",temperature.max())
print("Minimum temperatures:",temperature.min())

#Number of days above the average temperature
print("Number of days above the average temperature: ",temperature[temperature>=temperature.mean()])

#Temperatures greater than 34°C
print("Temperatures greater than 34°C:", temperature[temperature>34])

#Difference between maximum and minimum
print("Difference between maximum and minimum:", temperature.max()-temperature.min())

#Standard deviation
print("Standard Deviation:", temperature.std())


Mean temperature: 33.142857142857146
Maximum temperatures: 37
Minimum temperatures: 29
Number of days above the average temperature:  [35 36 34 35 37 36]
Temperatures greater than 34°C: [35 36 35 37 36]
Difference between maximum and minimum: 8
Standard Deviation: 2.356060357495806


In [ ]:
#13. Monthly sales of a company are:
sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])

#Determine:

import calendar

#Total annual sales
print("Total annual sales:", sales.sum())

#Average monthly sales
print("Average annual sales:", sales.mean())

#Month with the highest sales
print("Month with the highest sales:", calendar.month_name[np.argmax(sales) + 1])

#Month with the lowest sales
print("Month with the highest sales:", calendar.month_name[np.argmin(sales) + 1])

#Number of months with sales above ₹20,000
print("Number of months with sales above ₹20,000:", sales[sales>20000].size)

#Percentage increase from January to December
print("Percentage increase from January to December:", (sales.max()/sales.min())*100)

#Hint: Remember that NumPy indexing starts at 0, while month numbering normally starts at 1.


Total annual sales: 240000
Average annual sales: 20000.0
Month with the highest sales: December
Month with the highest sales: January
Number of months with sales above ₹20,000: 6
Percentage increase from January to December: 233.33333333333334


In [69]:
#14. Consider marks of five students in four subjects:

marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])

#Write a NumPy program that calculates:

#Total marks of every student
print("Total marks of every student:", marks.max(1))

#Average of every student
print("Average of every student:", marks.mean(1))

#Average mark for every subject
print("Average of every subject:", marks.mean(0))

#Highest-scoring student
print("Highest-scoring student index:", np.argmax(marks.sum(1)))

#Lowest-scoring student
print("Lowest-scoring student index:", np.argmin(marks.sum(1)))

#Students whose average is greater than 80
avgmarks=marks.mean(1)
print("Students whose average is greater than 80:", np.where(marks.mean(1) >= 80)[0])

#Overall class average
print("Overall class average:", marks.mean())

#Then assign a performance category based on average:

#|  Average | Category          |
#| -------: | ----------------- |
#|     ≥ 85 | Excellent         |
#| 70–84.99 | Good              |
#| 50–69.99 | Average           |
#|     < 50 | Needs Improvement |

#Challenge: Try assigning these categories using np.where() or np.select() instead of a Python loop.
print("\nOverall class catergories:")
allavg=marks.mean(1)
category=categories = np.select(
    [
        allavg >= 85,
        allavg >= 70,
        allavg >= 50
    ],
    [
        "Excellent",
        "Good",
        "Average"
    ],
    default="Needs Improvement"
)
print(category)

#tabular form
print("\n\tAverage | Category\n",'-' * 40)
for i in range(marks.shape[0]):
    print(f"\t{allavg[i]:.2f}   |  {category[i]}")

Total marks of every student: [90 72 95 62 82]
Average of every student: [85.25 68.75 91.5  58.75 79.  ]
Average of every subject: [74.  75.6 79.4 77.6]
Highest-scoring student index: 2
Lowest-scoring student index: 3
Students whose average is greater than 80: [0 2]
Overall class average: 76.65

Overall class catergories:
['Excellent' 'Average' 'Excellent' 'Average' 'Good']

	Average | Category
 ----------------------------------------
	85.25   |  Excellent
	68.75   |  Average
	91.50   |  Excellent
	58.75   |  Average
	79.00   |  Good


In [84]:
#15. Generate 20 random integers between 1 and 100.
randlist=np.random.randint(0,101,20)
print(randlist.reshape([20,1]))

[[14]
 [89]
 [90]
 [49]
 [73]
 [96]
 [87]
 [87]
 [99]
 [85]
 [94]
 [93]
 [81]
 [15]
 [13]
 [53]
 [79]
 [ 2]
 [98]
 [78]]


In [85]:
#16. Find all even numbers from the generated array.
randlist[randlist%2 == 0]

array([14, 90, 96, 94,  2, 98, 78])

In [86]:
#17. Replace values below 50 with 0.
randlist[randlist<50]=0
randlist

array([ 0, 89, 90,  0, 73, 96, 87, 87, 99, 85, 94, 93, 81,  0,  0, 53, 79,
        0, 98, 78])

In [98]:
#18. Sort the array in ascending and descending order.
#a. Ascending
print(np.sort(randlist))
#b. Descending
print(np.sort(randlist)[::-1])

[ 0  0  0  0  0 53 73 78 79 81 85 87 87 89 90 93 94 96 98 99]
[99 98 96 94 93 90 89 87 87 85 81 79 78 73 53  0  0  0  0  0]


In [102]:
#19. Find unique values and their frequencies.
np.unique(randlist)

array([ 0, 53, 73, 78, 79, 81, 85, 87, 89, 90, 93, 94, 96, 98, 99])

In [115]:
#20. Create a 5 × 5 random matrix and calculate row-wise and column-wise means.
randmatrix=np.random.randint(0,5,[5,5])
print(randmatrix)
print("Rowwise mean:\n", randmatrix.mean(1).reshape([5,1]))
print("Columnwise mean:\n", randmatrix.mean(0).reshape([5,1]))

[[2 2 1 3 0]
 [0 2 3 3 1]
 [2 0 2 0 1]
 [1 1 2 0 0]
 [2 4 3 2 1]]
Rowwise mean:
 [[1.6]
 [1.8]
 [1. ]
 [0.8]
 [2.4]]
Columnwise mean:
 [[1.4]
 [1.8]
 [2.2]
 [1.6]
 [0.6]]


In [123]:
#21. Take your own example to normalize an array. 
normform = (randlist - randlist.mean())/randlist.std()
normform

array([-1.67362924, -1.67362924, -1.67362924, -1.67362924, -1.67362924,
       -0.28981723,  0.23237598,  0.36292428,  0.38903394,  0.44125326,
        0.54569191,  0.59791123,  0.59791123,  0.65013055,  0.67624021,
        0.75456919,  0.78067885,  0.83289817,  0.88511749,  0.91122715])

In [ ]:
#22. Use your own data to standardize an array. 
randlist.std()

38.300000000000004

In [129]:
#23. Create a NumPy array containing 100 random exam marks and determine how many students fall into the ranges 0–39, 40–59, 60–79, and 80–100.
randmarks = np.random.randint(0,101,100)
markrange=np.select(
    [randmarks >=80,
     randmarks >= 60,
     randmarks >= 40
    ],
    [
        "80-100",
        "60-79",
        "40-59"
    ],
    default="0-39"
)
vals,counts = np.unique(markrange, return_counts=True)
print(dict(zip(vals,counts)))

{'0-39': 39, '40-59': 20, '60-79': 23, '80-100': 18}


In [ ]:
#24. Compare the time required to multiply 1,000,000 numbers using a Python list and a NumPy array.

In [139]:
one = [1]*1000000
onenp=np.ones(1000000)

In [140]:
one = [x * 2 for x in one]
one[1:10]

[2, 2, 2, 2, 2, 2, 2, 2, 2]

In [141]:
onenp = onenp * 2
onenp[1:10]

array([2., 2., 2., 2., 2., 2., 2., 2., 2.])