In [2]:
import numpy as np

In [3]:
# 1. Create a constant array
#  prints "[[7. 7.]]
#           [7. 7]]"
np.ones([2,2], float) *7

array([[7., 7.],
       [7., 7.]])

In [4]:
# 2. Create an array filled with random values
# Might print "[[0.91949167 0.08143941]
#               [0.68744134 0.87236687]]"

#method 1
print(np.random.randint(0,10**8,(2,2))/(10**8))

#Method 2
print(np.random.default_rng().random([2,2]))

[[0.18354186 0.79611731]
 [0.11183459 0.55115406]]
[[0.54464165 0.6308153 ]
 [0.22748482 0.33486346]]


In [5]:
# 3.Create a NumPy array containing the numbers from 10 to 50. Display:
# a. The array
# b. Number of elements
# c. Shape
# d. Dimension
# e. Data type

# a. The array
l = np.arange(10,50).reshape([4,10])
print("Array:",l)

# b. Number of elements
print("Number of elements in the array:", l.size)

# c. Shape
print("Shape of array:", l.shape)

# d. Dimension
print("Dimension of array:", l.ndim)

# e. Data type
print("Datatype of array:", l.dtype)


Array: [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Number of elements in the array: 40
Shape of array: (4, 10)
Dimension of array: 2
Datatype of array: int32


In [6]:
# 4. Using NumPy, create: 
# a. 1D array containing 10 zeroes
# b. 3 x 3 array contain ones
# c. 4 x 4 identity matrix
# d. An array containing numbers from 5 to 50 with a step size of 5.

# a. 1D array containing 10 zeroes
print("1D array containing 10 zeroes:",np.repeat([0],10))

# b. 3 x 3 array contain ones
print("3 x 3 array contain ones:\n", np.ones([3,3], int))

# c. 4 x 4 identity matrix
print("4 x 4 identity matrix:\n", np.ones([4,4], int))

# d. An array containing numbers from 5 to 50 with a step size of 5.
print("An array contiaining numbers from 5 to 50 with a step size of 5:", np.arange(5,55,5))

1D array containing 10 zeroes: [0 0 0 0 0 0 0 0 0 0]
3 x 3 array contain ones:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
4 x 4 identity matrix:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
An array contiaining numbers from 5 to 50 with a step size of 5: [ 5 10 15 20 25 30 35 40 45 50]


In [7]:
# 5. Create an array containing numbers from 1 tp 24. Reshape it into:
# a. 4 x 6
# b. 6 x 4
# c. 2 x 3 x 4

# a. 4 x 6
xyz = np.arange(1,25).reshape([4,6])
print("Shape:",xyz.shape,"Dim:",xyz.ndim,"\n", xyz)
print("\n")

# b. 6 x 4
xyzT = xyz.T
print("Shape:",xyzT.shape,"Dim:",xyzT.ndim,"\n", xyz.T)
print("\n")

# c. 2 x 3 x 4
xyz234=xyz.reshape([2,3,4])
print("Shape:",xyz234.shape,"Dim:",xyz234.ndim,"\n", xyz234)

Shape: (4, 6) Dim: 2 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


Shape: (6, 4) Dim: 2 
 [[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]


Shape: (2, 3, 4) Dim: 3 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [8]:
# 6. Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
# Write NumPy statements to display:
# a. First element
# b. Last element
# c. Third element
# d. First four elements
# e. Last three elements

marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
# a. First element
print("First element:", marks[0])

# b. Last element
print("Last element:", marks[-1])

# c. Third element
print("First element:", marks[2])

# d. First four elements
print("First four element:", marks[:4])

# e. Last three elements
print("Last three element:", marks[-3:])

First element: 78
Last element: 81
First element: 92
First four element: [78 85 92 67]
Last three element: [73 95 81]


In [9]:
# 7. Create:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

# Calculate
# a + B
print("a + b:",a + b)

# a - b
print("a - b:",a - b)

# a * b
print("a * b:",a * b)

# a / b
print("a / b:",a / b)

a + b: [15 30 45 60 75]
a - b: [ 5 10 15 20 25]
a * b: [  50  200  450  800 1250]
a / b: [2. 2. 2. 2. 2.]


In [10]:
# 8. Given:
salary = np.array([25000, 32000, 28000, 45000, 50000, 38000, 42000, 30000])

# Find:
# Total Salary
print("Total Salary:", salary.sum())

# Average Salary
print("Average Salary:", salary.mean())

# Highest Salary
print("Highest Salary:", salary.max())

# Lowest Salary
print("Lowest Salary:", salary.min())

# Median Salary
print("Median Salary:", np.median(salary))

# Standard Deviation
print("Standard Deviation:", salary.std())

Total Salary: 290000
Average Salary: 36250.0
Highest Salary: 50000
Lowest Salary: 25000
Median Salary: 35000.0
Standard Deviation: 8317.902379807063


In [11]:
# 9. Given:
marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])
#Using NumPy boolean indexing, find:

# a. Marks greater than 75
print("Marks greater than 75:",marks[marks>75])

# b. Marks between 50 and 80
print("Marks between 50 and 80:",marks[(marks>50) & (marks<80)])

# c. Number of students who scored below 50
print("Number of students who scored below 50:", marks[marks<50].size)

# d. Percentage of students who scored 60 or above
print("Percentage of students who scored 60 or above:", (marks[marks>=60].size/marks.size)*100, "%")

Marks greater than 75: [78 89 90 76 84]
Marks between 50 and 80: [78 67 55 76]
Number of students who scored below 50: 3
Percentage of students who scored 60 or above: 60.0 %


In [20]:
#10. The following array contains marks of four students in three subjects:

marks = np.array([
    [80, 95, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])

#Calculate:

#Total marks of each student
#Average marks of each student
#Average marks in each subject
#Student with the highest total
#Highest mark in each subject.

#Total marks of each student
student_total = np.sum(marks, axis=1)
print("Total of each student:", student_total)



#Average marks of each student
meanstud = np.mean(marks, axis=1)
print("Mean of each student:", meanstud)

#Average marks in each subject
meansub = np.mean(marks, axis=0)
print("Mean of each student:", meansub)

#Student with the highest total
argmaxstud = np.argmax(student_total)
print("Max student:", argmaxstud)

#Highest mark in each subject.
argmaxstud = np.argmax(marks, axis=0)
print("Max subject:", argmaxstud)

Total of each student: [265 207 265 173]
Mean of each student: [88.33333333 69.         88.33333333 57.66666667]
Mean of each student: [72.   79.25 76.25]
Max student: 0
Max subject: [2 0 0]
